# Python Modules

### Numpy Module

In [254]:
import numpy as np
print(np.__version__)
print(np.version)

2.3.3
<module 'numpy.version' from 'c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\numpy\\version.py'>


In [255]:
import numpy as np
a= np.array([1,2,3,4,5,6,7,8,9])
print(a)
print(type(a))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [256]:
import numpy as np
a = np.array((1,2,3,"a","b","c"))
print(a)
print(type(a))

['1' '2' '3' 'a' 'b' 'c']
<class 'numpy.ndarray'>


In [257]:
import numpy as np
a = np.array([[1,2],[2,3],[3,4]])
print(a)
print("dimension:",a.ndim,"D")

[[1 2]
 [2 3]
 [3 4]]
dimension: 2 D


In [258]:
import numpy as np
a = np.array([[[1,2],[2,3],],[[3,4],[4,5]],[[5,6],[6,7]]])
print(a)
print("demension:",a.ndim,"D")

[[[1 2]
  [2 3]]

 [[3 4]
  [4 5]]

 [[5 6]
  [6 7]]]
demension: 3 D


In [259]:
import numpy as np
a = np.array([1,2,3,4,5,6,7])
print(a[1])
print(a[3])
print("index addition",a[1]+a[3])

2
4
index addition 6


In [260]:
import numpy as np 
a= np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("2D element:",a[0,3])
print("2D element:",a[1,3])

2D element: 4
2D element: 9


In [261]:
import numpy as np
a= np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]],[[17,18,19,20],[21,22,23,24]]])
print("3D element:",a[0,0,2])
print("3D element:",a[1,1,1])
print("3D element:",a[2,1,2])

3D element: 3
3D element: 14
3D element: 23


In [262]:
import numpy as np 
a= np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("Negative Index")
print("2D element:",a[1,-2])

Negative Index
2D element: 9


In [263]:
import numpy as np
a = np.array([1,2,3,4,5,6,7])
print(a[2:5])

[3 4 5]


In [264]:
import numpy as np
a = np.array([1,2,3,4,5,6,7])
print(a[1:5:2])

[2 4]


In [265]:
import numpy as np
a = np.array([1,2,3,4,5,6,7])
print(a[::2])

[1 3 5 7]


In [266]:
import numpy as np
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a[1,1:4])

[7 8 9]


In [267]:
import numpy as np
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a[0:3,3])

[4 9]


In [268]:
import numpy as np
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [269]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a.dtype)

int64


In [270]:
import numpy as np
a = np.array(['a','b','c','d','e'])
print(a.dtype)

<U1


In [271]:
import numpy as np
a = np.array([1,2,3,4,5],dtype='S')
print(a)
print(a.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [272]:
import numpy as np
a = np.array([1,2,3,4,5],dtype='i4')
print(a)
print(a.dtype)

[1 2 3 4 5]
int32


In [273]:
import numpy as np
arr = np.array([1.1,2.1,3.1,4.1,5.1])
newarr = arr.astype('i')  # 'i' ne jagyaye int pan lakhi shaku
print(arr)
print(arr.dtype)
print(newarr)
print(newarr.dtype)

[1.1 2.1 3.1 4.1 5.1]
float64
[1 2 3 4 5]
int32


In [274]:
import numpy as np
arr= np.array([1,2,3,4,5])
x= arr.copy()
arr[0] = 0
print(x)
print(arr)

[1 2 3 4 5]
[0 2 3 4 5]


In [275]:
import numpy as np
arr= np.array([1,2,3,4,5])
x= arr.view()
arr[0] = 0
print(x)
print(arr)

[0 2 3 4 5]
[0 2 3 4 5]


In [276]:
import numpy as np
arr= np.array([1,2,3,4,5])
x= arr.copy()
y= arr.view()
print(x.base) # x na potana data che (own data) etale base none return kare
print(y.base) # y data batave che potana data nathi (not own data) etale base none return no kare list print kare

None
[1 2 3 4 5]


In [277]:
import numpy as np
a= np.array([1,2,3,4,5])
b= np.array([[1,2,3],[1,2,3],[1,2,3]])
c= np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
print(a.shape) # shape index return kare
print(b.shape)
print(c.shape)

(5,)
(3, 3)
(3, 2, 3)


In [278]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [279]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(3,2,2)
print(newarr)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [280]:
import numpy as np
arr = np.array([[1, 2, 3, 4],[ 5, 6, 7, 8]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6 7 8]


In [281]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
for i in arr:
    print(i)

1
2
3
4
5
6
7
8


In [282]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
for i in arr:
    print(i)

[1 2 3 4]
[5 6 7 8]


In [283]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
for i in arr:
    for j in i:
        print(j, end="      ")

1      2      3      4      5      6      7      8      

In [284]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for i in arr:
    print(i)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [285]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for i in arr:
    for j in i:
        for k in j:
            print(k, end="  ")

1  2  3  4  5  6  7  8  9  10  11  12  

In [286]:
import numpy as np
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6 7 8]


In [287]:
import numpy as np
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr = np.concatenate((arr1,arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [288]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.stack((arr1,arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [289]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.hstack((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [290]:
import numpy as np 
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.vstack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [291]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.dstack((arr1,arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [292]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [293]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [294]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [295]:
import numpy as np
arr = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr = np.array_split(arr,3)
print(newarr)
for i in newarr:
    print(i)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


In [296]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
newarr = np.array_split(arr, 3, axis=1)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [297]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
newarr = np.hsplit(arr, 3)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [298]:
import numpy as np
arr= np.array([1,2,3,4,5,6,4,4])
newarr = np.where(arr == 4)
print(newarr)

(array([3, 6, 7]),)


In [299]:
import numpy as np
arr= np.array([22,23,55,66,87,64,87,76])
print("even:",np.where(arr%2 == 0))
print("odd:",np.where(arr%2 == 1))

even: (array([0, 3, 5, 7]),)
odd: (array([1, 2, 4, 6]),)


In [300]:
import numpy as np
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 9)
print(x)

3


In [301]:
import numpy as np
arr = np.array([3,7,9,6])
newarr = np.searchsorted(arr, 7, side="right")
print(newarr)

2


In [302]:
import numpy as np 
arr = np.array([1,3,5,7])
x= np.searchsorted(arr, [2,4,6])
print(x)

[1 2 3]


In [303]:
import numpy as np
arr = np.array([1,4,2,0,5,7,6])
new= np.sort(arr)
print(new)

[0 1 2 4 5 6 7]


In [304]:
import numpy as np
arr = np.array(['banana','mango','apple','kiwi','cherry'])
print(np.sort(arr))

['apple' 'banana' 'cherry' 'kiwi' 'mango']


In [305]:
import numpy as np 
arr = np.array([True,False,True,False,False]) # False means 0 and True means 1
new= np.sort(arr)
print(new)

[False False False  True  True]


In [306]:
import numpy as np
arr = np.array([[5,1,9],[8,2,0]])
new= np.sort(arr)
print(new)

[[1 5 9]
 [0 2 8]]


In [307]:
import numpy as np
arr = np.array([41,42,43,44])
x = [True,False,True,False] #41=True 42=False 43=True 44=False only True print thay che
newarr = arr[x]
print(newarr)

[41 43]


### Pandas Module

In [312]:
import pandas as pd
mydata= {
    'cars' : ['toyota','volvo','fortuner'],
    'models' : [2021,2025,2020]
}
x = pd.DataFrame(mydata)
print(x)

       cars  models
0    toyota    2021
1     volvo    2025
2  fortuner    2020


In [316]:
import pandas as pd
a= [1,7,2]
myvar = pd.Series(a,index=["a","b","c"])
print(myvar)

a    1
b    7
c    2
dtype: int64


In [317]:
import pandas as pd
categories = {"day1":420,"day2":360,"day3":390}
x= pd.Series(categories)
print(x)

day1    420
day2    360
day3    390
dtype: int64


In [318]:
import pandas as pd
categories = {"day1":420,"day2":360,"day3":390}
x= pd.Series(categories, index=["day1","day2"])
print(x)

day1    420
day2    360
dtype: int64


In [325]:
import pandas as pd
data ={
    "calories": [420,380,390],
    "durations": [50,45,40]
}
df = pd.DataFrame(data)
print(df)

   calories  durations
0       420         50
1       380         45
2       390         40


In [331]:
import pandas as pd
data= {
    "calories": [420,360,390],
    "durations": [50,45,40]
}
df = pd.DataFrame(data)
print(df.loc[[0,1]]) # print(df.loc[[0,1,2]]) 0,1,2 index na data print kare

   calories  durations
0       420         50
1       360         45


In [333]:
import pandas as pd
data= {
    "calories": [420,360,390],
    "durations": [50,45,40]
}
df = pd.DataFrame(data, index=['day1','day2','day3'])
print(df)

      calories  durations
day1       420         50
day2       360         45
day3       390         40


In [335]:
import pandas as pd 
data ={
    "calories": [423,735,554],
    "durations": [34,65,54]
}
df = pd.DataFrame(data, index=["day1","day2","day3"])
print(df.loc['day2'])

calories     735
durations     65
Name: day2, dtype: int64


In [349]:
# data.csv file are connect this file
import pandas as pd
df= pd.read_csv('data.csv')
# print(df.to_string())
print(df)

   rno     name        city
0    1    mohan       surat
1    2    manan      amreli
2    3    manav    junagadh
3    4   mayank      rajkot
4    5    mayur        pune
5    6    mohit      rajkot
6    7   jaydip    bagasara
7    8  varshil      paniya
8    9      ram   ahemdabad
9   10    parth  gariyadhar


In [348]:
import pandas as pd 
print(pd.options.display.max_rows)

60


In [ ]:
import pandas as pd
pd.options.display.max_rows = 9999
x = pd.read_csv("data.csv")
print(x)

   rno     name        city
0    1    mohan       surat
1    2    manan      amreli
2    3    manav    junagadh
3    4   mayank      rajkot
4    5    mayur        pune
5    6    mohit      rajkot
6    7   jaydip    bagasara
7    8  varshil      paniya
8    9      ram   ahemdabad
9   10    parth  gariyadhar


In [370]:
# this file are connected to data.json file
import pandas as pd
df = pd.read_json("data.json")
# print(df.to_string())
print(df)

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.5
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45   

In [369]:
import pandas as pd 
data= {
    "Duration": {
        "0":00,
        "1":10,
        "2":20,
        "3":30,
        "4":40,
        "5":50
    },
    "Pulse": {
        "0":100,
        "1":110,
        "2":120,
        "3":130,
        "4":140,
        "5":150
    },
    "Maxpulse": {
        "0":200,
        "1":210,
        "2":220,
        "3":230,
        "4":240,
        "5":250,
    },
    "Calories": {
        "0":300,
        "1":310,
        "2":320,
        "3":330,
        "4":340,
        "5":350
    }
}
df = pd.DataFrame(data)
print(df)

   Duration  Pulse  Maxpulse  Calories
0         0    100       200       300
1        10    110       210       310
2        20    120       220       320
3        30    130       230       330
4        40    140       240       340
5        50    150       250       350


In [ ]:
import pandas as pd
df = pd.read_csv('data.csv')
print(df.head(6))   # head(6) 6 data is printed  |  only head() first 5 record display

   rno    name      city
0    1   mohan     surat
1    2   manan    amreli
2    3   manav  junagadh
3    4  mayank    rajkot
4    5   mayur      pune
5    6   mohit    rajkot


In [ ]:
import pandas as pd
df = pd.read_csv("data.csv")
print(df.tail())   # tail(7) last 7 row data is printed  |  only tail() last 5 row data display

   rno     name        city
5    6    mohit      rajkot
6    7   jaydip    bagasara
7    8  varshil      paniya
8    9      ram   ahemdabad
9   10    parth  gariyadhar


In [ ]:
import pandas as pd 
x= pd.read_csv("data.csv")
print(x.info())  # info() method are print info csv file

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   rno     10 non-null     int64 
 1   name    10 non-null     object
 2   city    10 non-null     object
dtypes: int64(1), object(2)
memory usage: 372.0+ bytes
None


In [434]:
import pandas as pd
df = pd.read_csv('data.csv')
df.dropna(inplace = True)
print(df)

   rno     name        city
0    1    mohan       surat
1    2    manan      amreli
2    3    manav    junagadh
3    4   mayank      rajkot
4    5    mayur        pune
5    6    mohit      rajkot
6    7   jaydip    bagasara
7    8  varshil      paniya
9   10    parth  gariyadhar


In [432]:
import pandas as pd
df = pd.read_csv('data.csv')
df.fillna("ram", inplace = True)
print(df.to_string())

   rno     name        city
0    1    mohan       surat
1    2    manan      amreli
2    3    manav    junagadh
3    4   mayank      rajkot
4    5    mayur        pune
5    6    mohit      rajkot
6    7   jaydip    bagasara
7    8  varshil      paniya
8    9      ram   ahemdabad
9   10    parth  gariyadhar


In [437]:
import pandas as pd
df = pd.read_csv("data.csv")
df.fillna({"name":"monank"},inplace=True)
print(df)

   rno     name        city
0    1    mohan       surat
1    2    manan      amreli
2    3    manav    junagadh
3    4   mayank      rajkot
4    5    mayur        pune
5    6    mohit      rajkot
6    7   jaydip    bagasara
7    8  varshil      paniya
8    9   monank   ahemdabad
9   10    parth  gariyadhar


In [439]:
import pandas as pd 
df = pd.read_csv("data.csv")
x=df["rno"].mean()
df.fillna({"name":x},inplace=True) # 1+2+..+10 = 55/10 = 5.5
print(df.to_string())

   rno     name        city
0    1    mohan       surat
1    2    manan      amreli
2    3    manav    junagadh
3    4   mayank      rajkot
4    5    mayur        pune
5    6    mohit      rajkot
6    7   jaydip    bagasara
7    8  varshil      paniya
8    9      5.5   ahemdabad
9   10    parth  gariyadhar


In [ ]:
import pandas as pd 
df = pd.read_csv("data.csv")
x=df["rno"].median()
df.fillna({"name":x},inplace=True) 
print(df.to_string())

   rno     name        city
0    1    mohan       surat
1    2    manan      amreli
2    3    manav    junagadh
3    4   mayank      rajkot
4    5    mayur        pune
5    6    mohit      rajkot
6    7   jaydip    bagasara
7    8  varshil      paniya
8    9      5.5   ahemdabad
9   10    parth  gariyadhar


In [ ]:
import pandas as pd 
df = pd.read_csv("data.csv")
x=df["rno"].mode()[1]          # [0]=1 , [1]=2 batave che
df.fillna({"name":x},inplace=True) 
print(df.to_string())

   rno     name        city
0    1    mohan       surat
1    2    manan      amreli
2    3    manav    junagadh
3    4   mayank      rajkot
4    5    mayur        pune
5    6    mohit      rajkot
6    7   jaydip    bagasara
7    8  varshil      paniya
8    9        2   ahemdabad
9   10    parth  gariyadhar


In [490]:
import pandas as pd
df = pd.read_csv("data.csv")
df.drop_duplicates(inplace=True)
print(df)
# print(df[df.duplicated()]) # deleted recoed display

   rno     name       city
0    1    mohan      surat
1    2    manan     amreli
2    3    manav   junagadh
3    4   mayank     rajkot
4    5    mayur       pune
5    6    parth     rajkot
6    7   jaydip   bagasara
7    8  varshil     paniya
8    9      NaN  ahemdabad


### SciPy Module

In [494]:
from scipy import constants
print(constants.liter)

0.001


In [495]:
import scipy
print(scipy.__version__)

1.17.1


In [497]:
from scipy import constants
print(constants.pi)

3.141592653589793


In [498]:
from scipy import constants
print(dir(constants))

['Avogadro', 'Boltzmann', 'Btu', 'Btu_IT', 'Btu_th', 'ConstantWarning', 'G', 'Julian_year', 'N_A', 'Planck', 'R', 'Rydberg', 'Stefan_Boltzmann', 'Wien', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_codata', '_constants', '_obsolete_constants', 'acre', 'alpha', 'angstrom', 'arcmin', 'arcminute', 'arcsec', 'arcsecond', 'astronomical_unit', 'atm', 'atmosphere', 'atomic_mass', 'atto', 'au', 'bar', 'barrel', 'bbl', 'blob', 'c', 'calorie', 'calorie_IT', 'calorie_th', 'carat', 'centi', 'codata', 'constants', 'convert_temperature', 'day', 'deci', 'degree', 'degree_Fahrenheit', 'deka', 'dyn', 'dyne', 'e', 'eV', 'electron_mass', 'electron_volt', 'elementary_charge', 'epsilon_0', 'erg', 'exa', 'exbi', 'femto', 'fermi', 'find', 'fine_structure', 'fluid_ounce', 'fluid_ounce_US', 'fluid_ounce_imp', 'foot', 'g', 'gallon', 'gallon_US', 'gallon_imp', 'gas_constant', 'gibi', 'giga', 'golden', 'golden_ratio', 'grain', '

In [524]:
from scipy import constants
print(constants.yotta)
print(constants.zetta)
print(constants.exa)
print(constants.peta)
print(constants.tera)
print(constants.giga)
print(constants.mega)
print(constants.kilo)
print(constants.hecto)
print(constants.deka)
print(constants.deci)
print(constants.centi)
print(constants.milli)
print(constants.micro)
print(constants.nano)
print(constants.pico)
print(constants.femto)
print(constants.atto)
print(constants.zepto)

1e+24
1e+21
1e+18
1000000000000000.0
1000000000000.0
1000000000.0
1000000.0
1000.0
100.0
10.0
0.1
0.01
0.001
1e-06
1e-09
1e-12
1e-15
1e-18
1e-21


In [532]:
from scipy import constants
print("minute convert to second:",constants.minute)
print("hour convert to second:",constants.hour)
print("day convert to second:",constants.day)
print("week convert to second:",constants.week)
print("year convert to second:",constants.year)
print("julian year convert to second:",constants.Julian_year)

minute convert to second: 60.0
hour convert to second: 3600.0
day convert to second: 86400.0
week convert to second: 604800.0
year convert to second: 31536000.0
julian year convert to second: 31557600.0
