## Numpy in Python 

In [ ]:
# using numpy array
import numpy as np

a1 = np.array([1,2,3,4,5,6])
a2 = np.array([
        [1,2,3],[4,5,6]
    ])
a3 = np.array([
        [[1,2,3],[4,5,6]],
        [[7,8,9],[10,11,12]]
    ])

print("1D array")
print(a1)
print("\n2D array")
print(a2)
print("\n3D array")
print(a3)

1D array
[1 2 3 4 5 6]

2D array
[[1 2 3]
 [4 5 6]]

3D array
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
# using numpy function array
import numpy as np

a0 = np.zeros((3))
a1 = np.ones((3))
ar = np.arange(0,7)
print(a0)
print(a1)
print(ar)

[0. 0. 0.]
[1. 1. 1.]
[0 1 2 3 4 5 6]


In [190]:
# using numpy function array
import numpy as np

a0 = np.zeros((3, 5))
a1 = np.ones(((3, 4, 2)))
print(a0)
print(a1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [ ]:
# Attribute
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
print("shape: ", a.shape)   # (row, column)
print("datatype: ", a.dtype)   # datatype
print("dimension: ", a.ndim)    # dimension

shape:  (2, 3)
datatype:  int64
dimension:  2


In [ ]:
# indexing
import numpy as np

a1 = np.array([11,22,33,44,55,66])
a2 = np.array([[11,22,33],
               [44,55,66]])

print(a1[2])
print(a1[-1])
print(a2[1])
print(a2[1][1])

33
66
[44 55 66]
55


In [ ]:
# slicing
import numpy as np

a1 = np.array([[1,2,3],
               [4,5,6]])
print(a1[0:1])  # row slicing
print(a1[1:2])  # row slicing
print(a1[:])    # all row slicing
print(a1[:, 1])  # all row, 1 column element slicing
print(a1[:, 0:2])  # all row, 0 and 1 column element slicing

[[1 2 3]]
[[4 5 6]]
[[1 2 3]
 [4 5 6]]
[2 5]
[[1 2]
 [4 5]]


In [54]:
# advance indexing
import numpy as np

a = np.array([10,20,30,40,50,60])
b = np.array([1,3,5])
print(a[b])

c = a > 30
print(a[c])

[20 40 60]
[40 50 60]


In [60]:
# basic arithmetic operation
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)
print(a - b)
print(a * b)
print(a ** b)
print(a / b)
print(a // b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[  1  32 729]
[0.25 0.4  0.5 ]
[0 0 0]


In [62]:
# unary operator
import numpy as np
a = np.array([-5, -2, 0, 3, 7])
print(a)
b = np.absolute(a)
print(b)

[-5 -2  0  3  7]
[5 2 0 3 7]


In [ ]:
# binary operator
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

add = np.add(a, b)
sub = np.subtract(a, b)
mul = np.multiply(a, b)
div = np.divide(a, b)
print(add)
print(sub)
print(mul)
print(div)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [74]:
# binary operator
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

a += b
print(a)

[5 7 9]


In [78]:
# binary operator
import numpy as np
a = np.array([1,2,3])
b = np.array([4])

a *= b
print(a)

[ 4  8 12]


In [86]:
# mathematical operation
import numpy as np

a = np.array([0, np.pi/2, np.pi])
print(a)
print(np.sin(a))

b = np.array([0,1,2,3])
print(np.exp(b))
print(np.sqrt(b))

print(np.sqrt(a))


[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.          2.71828183  7.3890561  20.08553692]
[0.         1.         1.41421356 1.73205081]
[0.         1.25331414 1.77245385]


In [ ]:
# sort method
import numpy as np

dtype = [('name', 'S20'), ('year', int), ('cgpa', float)]

vals = [("dip", 2008, 8.8),
        ("man", 2005, 7.4),
        ("jay", 2005, 7.9),
        ("ram", 2006, 6.8)]

print("without sorting")
a = np.array(vals, dtype=dtype)
print(a)

print("name sorting")
print(np.sort(a, order='name'))
print("year and name sorting")
print(np.sort(a, order=['year','name']))

without sorting
[(b'dip', 2008, 8.8) (b'man', 2005, 7.4) (b'jay', 2005, 7.9)
 (b'ram', 2006, 6.8)]
name sorting
[(b'dip', 2008, 8.8) (b'jay', 2005, 7.9) (b'man', 2005, 7.4)
 (b'ram', 2006, 6.8)]
year and name sorting
[(b'jay', 2005, 7.9) (b'man', 2005, 7.4) (b'ram', 2006, 6.8)
 (b'dip', 2008, 8.8)]


In [227]:
import numpy as np
a = ["a","c","x","p","w","q","e"]
print(np.sort(a))

['a' 'c' 'e' 'p' 'q' 'w' 'x']


In [198]:
# reshape array
import numpy as np 
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a1 = arr.reshape(4,3)
print(a1)
a2 = arr.reshape(3,2,2)
print(a2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [231]:
# split array
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
new = np.array_split(arr, 3)
print(new)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [203]:
import numpy as np
arr = np.array(["apple","banana","mango","kiwi","orange","pineapple","cherry","chikoo"])
new = np.array_split(arr, 4)
print(new)

[array(['apple', 'banana'], dtype='<U9'), array(['mango', 'kiwi'], dtype='<U9'), array(['orange', 'pineapple'], dtype='<U9'), array(['cherry', 'chikoo'], dtype='<U9')]


In [208]:
# searching array
import numpy as np
a = np.array([1,2,3,4,5,3,6,3])
x = np.where(a == 3)
print(x)

(array([2, 5, 7]),)


In [213]:
import numpy as np
a = np.array([43,42,21,54,23,65,22,91,98,54])
x = np.where(a%2 == 0)
print(x)

(array([1, 3, 6, 8, 9]),)


In [224]:
# search sorted
import numpy as np
a = np.array([43,42,21,56,23,65,22,91,98,54])
x = np.searchsorted(a, 91)
print(x)

7


In [ ]:
# filter array
import numpy as np
a = np.array([43,42,21,56,23,65,22,91,98,54])
even = []
odd = []

for i in a:
    if i%2 == 0:
        even.append(i)
    else:
        odd.append(i)

x = np.array(even)
y = np.array(odd)
print(x)
print(y)

[42 56 22 98 54]
[43 21 23 65 91]
